version = "1.0"

[main]

[main.integration]
name.en = "Integration"
services = ["nginx", "__APP__-docservice", "__APP__-converter"]
[main.integration.allowed_urls]
ask.en = "List of web addresses authorized to integrate the OnlyOffice editor separated by space"
ask.fr = "Liste des adresses web autorisées à intégrer l'éditeur OnlyOffice séparées par un espace"
help.en = "Install the OnlyOffice connector to edit documents from Nextcloud."
help.fr = "Installez le connecteur OnlyOffice pour éditer des documents dans Nextcloud."
type = "string"
example = "https://cloud.yunohost.domain/nextcloud https://example.com"
[main.integration.reject_unauthorized]
ask.en = "Prevent unauthenticated requests"
ask.fr = "Empécher les requêtes non authentifiées"
type = "boolean"
yes = "true"
no = "false"
help.en = "In the general case you should keep this option activated. Disabling this option allows OnlyOffice to accept unauthenticated HTTPS requests, which can be useful if your server is not exposed to the internet and cannot obtain a Let's Encrypt certificate."
help.fr = "En général, vous devriez laisser cette option activée. Désactiver cette option permet à OnlyOffice d'accepter les requêtes HTTPS non authentifiées, ce qui peut être utile si votre serveur n'est pas exposé sur internet et ne peut pas obtenir de certificat Let's Encrypt."
bind = "rejectUnauthorized:__INSTALL_DIR__/config/local.json"

[main.auto_assembly]
name.en = "Automatic forcesaving"
services = ["__APP__-docservice"]
[main.auto_assembly.autoassembly_enable]
ask.en = "Enable automatic forcesaving"
type = "boolean"
yes = "true"
no = "false"
bind = "autoAssembly>enable:__INSTALL_DIR__/config/local.json"
help.en = "The automatic forcesaving will only be initiated after some changes were made to the document. The empty versions will not be forcesaved automatically. Additionally, file versioning needs to be implemented on the document management system's side for this parameter to work."

[main.auto_assembly.autoassembly_interval]
ask.en = "Interval time in minutes"
type = "string"
bind = "autoAssembly>interval:__INSTALL_DIR__/config/local.json"
help.en = "Defines the interval time in minutes for initiating the automatic forcesaving."
example = "5m"
pattern.regexp = '^\d+m$'
pattern.error = "Provide a value in minutes like '5m'"

[main.auto_assembly.autoassembly_step]
ask.en = "Delay in minutes between the intervals"
type = "string"
bind = "autoAssembly>step:__INSTALL_DIR__/config/local.json"
example = "1m"
pattern.regexp = '^\d+m$'
pattern.error = "Provide a value in minutes like '1m'"

[main.rebuild]
name.en = "Limitations"

	[main.rebuild.rebuild_without_limitations]
	ask.en = "Remove usage limitations"
	ask.fr = "Supprimer les limites d'usage"
	type = "boolean"
	default = 1
	help.en = "Recompile binaries in order to remove usage limitations (number of users, opened documents, smartphone usage). Note: the install and upgrade will be slower. After changing this setting you should trigger a force upgrade of this app by yourself to be effective." 
	help.fr = "Recompile les binaires afin de supprimer les limitations d'utilisation (nombre d'utilisateurs, documents ouverts, utilisation sur smartphone). NB: l'installation et la mise à jour seront plus lentes. Après avoir modifié ce paramètre, vous devez déclencher vous-même une mise à jour forcée de l'app pour que le changement soit éffectif." 
